name: scriptor
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
        tsan: [ON, OFF]
        exclude:
          - asan: ON
            tsan: ON
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        run: |
          python3 bootstrap.py --build_type ${{ matrix.config }}
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dscriptor_build_tests=ON -Dscriptor_enable_asan=${{ matrix.asan }} .
          cmake --build . -j 4 --config ${{ matrix.config }}
          ctest --verbose
