name: scriptor
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
        tsan: [ON, OFF]
        exclude:
          - asan: ON
            tsan: ON
          - asan: ON
            os: windows-latest
          - tsan: ON
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: install libsystemd-dev on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y libsystemd-dev
      - name: run tests
        run: |
          python3 bootstrap.py
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dscriptor_build_tests=ON -Dscriptor_enable_asan=${{ matrix.asan }} .
          cmake --build . -j --config ${{ matrix.config }}
          ctest --verbose
